config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index] do
    resources :appointments, only: [:new, :create]
  end

  # to delete
  resources :appointments, only: [:show, :index, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  # Defines the root path route ("/")
  # root "articles#index"
  get "/users/:id/booking_appointment", to: 'users#booking_appointment', as: 'booking_appointment'
  resources :users, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :qualifications
  has_many :procedures
  has_many :doctors_locations, dependent: :destroy
  has_many :locations, through: :doctors_locations
  has_many :appointments_as_patient, class_name: "Appointment", foreign_key: :patient_id
  has_many :appointments_as_doctor, class_name: "Appointment", foreign_key: :doctor_id
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
  validates :date_of_birth, presence: true, if: :user_is_patient?
  validates :gender, presence: true, if: :user_is_patient?
  validates :role, presence: true
  validates :past_interventions, presence: true, if: :user_is_patient?

  enum :role, [:patient, :doctor]

  private

  def user_is_patient?
    role == "patient"
  end

  def user_is_doctor?
    role == "doctor"
  end

  include PgSearch::Model
  pg_search_scope :search_by_specialty,
    against: [ :specialty ],
    using: {
      tsearch: { prefix: true } # <-- now `spceialty` will return something!
    }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @specialty = params[:specialty]
    @doctors = User.where(role: "doctor")
    if params[:specialty].present?
      @doctors = User.search_by_specialty(params[:specialty])
    end
    if @doctors.empty?
      @doctors = User.where(role: "doctor")
    end
    @locations = Location.all
      @markers = @locations.geocoded.map do |location|
        {
          lat: location.latitude,
          lng: location.longitude,
          info_window_html: render_to_string(partial: "info_window", locals: { location: location }),
        }
    end
  end

  def new
    # To create the patient
    @patient = User.new
  end

  def create
    @patient = User.new(params_user)
    @patient = User.find(params[:id])
    @patient.save!
    redirect_to users_path
  end

  def show
    @doctor = User.find(params[:id]) if User.where(role: "doctor")
    @doctor_appointments = User.find(@doctor.id).appointments_as_doctor
    @date = params[:appointment_date].to_date if params[:appointment_date]
    @procedure = Procedure.find(params[:procedure_id]).name if params[:procedure_id]
    @real_procedure = Procedure.find(params[:procedure_id]) if params[:procedure_id]
    @appointment = Appointment.new
    if params[:appointment_date]
      @doctor_appointments = @doctor_appointments.select do |appointment|
        appointment.start_time.to_date == @date
      end
    end
    @appointment = Appointment.new
    # ------look for  an appointment for the current doctor being shown------
    @appointments_doc = Appointment.where(doctor_id: @doctor.id)
    # ---------now  go through reviews looking for multiple appointments for that doctor---------
    @reviews = Review.where(appointment_id: @appointments_doc.ids)
    @markers = @doctor.locations.geocoded.map do |location|
      {
        lat: location.latitude,
        lng: location.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {location: location}),
      }
    end
  end

  def booking_appointment
    @doctor = User.find(params[:id])
    @doctor_appointments = User.find(@doctor.id).appointments_as_doctor
    @procedure = Procedure.find(params[:procedure_id]).name if params[:procedure_id]
    @real_procedure = Procedure.find(params[:procedure_id]) if params[:procedure_id]
    @date = params[:appointment_date].to_date if params[:appointment_date]
    if params[:appointment_date]
      @doctor_appointments = @doctor_appointments.select do |appointment|
        appointment.start_time.to_date == @date
      end
    end
    @appointment = Appointment.new
    @available_timings = (8..12).to_a + (14..17).to_a
    @unavailable_timings = []
    @doctor_appointments.each do |appt|
      @unavailable_timings << appt.start_time.hour
      @available_timings.delete(appt.start_time.hour)
      if appt.end_time.hour > appt.start_time.hour && appt.end_time.min.positive?
        @unavailable_timings << appt.end_time.hour
        @available_timings.delete(appt.end_time.hour)
      end
    end

    @available_timings.each_with_index do |hour, index|
      unless @available_timings[index + 2].nil?
        if @real_procedure.duration / 60.0 > 2 && @real_procedure.duration / 60.0 <= 3
          unless @available_timings[index + 1] - hour == 1 && @available_timings[index + 2] - @available_timings[index + 1] == 1
            @unavailable_timings << hour
          end
        end
      end
      unless @available_timings[index + 1].nil?
        if @real_procedure.duration / 60.0 > 1 && @real_procedure.duration / 60.0 <= 2
          unless @available_timings[index + 1] - hour == 1
            @unavailable_timings << hour
          end
        end
      end
    end
    @unavailable_timings.sort!.each { |time| @available_timings.delete(time) }
    # create an array of timeslots of one hour each
    # 8 to 13 and 14 to 18
  end

  private

  def params_user
    params.require(:user).permit(:first_name, :last_name, :bio, :email, :password, :phone_number, :specialty)
  end
end

app/views/users/_form.html.erb
<%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

app/views/users/_info_window.html.erb
<div class="info-w-wrapper p-3">
  <h3><%= location.name %></h3>
  <h6><%= location.address %></h6>
</div>

app/views/users/booking_appointment.html.erb
<div class="big-container" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/MiguelBelo95/Codeacademy/main/background_1.png); background-repeat: round;">
  <div class="blur">
  <div class="container">
    <div class="row justify-content-center">

        <div class="d-flex" style="background-color: #f1e9e4; margin: 1rem; border-radius: 5px;">
          <div class="show-page-photo-card mx-3">
            <%= image_tag @doctor.image_url, class: "m-3" %>
            <h2 class="m-0"><strong>Dr.<%= @doctor.first_name %> <%= @doctor.last_name %></strong></h2>
            <h2 class="mb-3"><%= @doctor.specialty %></h2>
          </div>
          <div class="m-3">
            <h5>Summary:</h5>
            <% if params[:procedure_id] %>
              <ul>
                <li>Appointment for: <%= @real_procedure.name %></li>
                <li>Duration: <%= @real_procedure.duration%> minutes</li>
                <li>Cost: £<%= number_with_delimiter(@real_procedure.price)%></li>
              </ul>
            <% end %>
          </div>
          <div style="margin: 1rem; text-align: right; flex-grow: 1;">
            <%= link_to user_path(@doctor), class: 'btn btn-sm' do %>
              <i class="fas fa-times"></i> <!-- You can use a close icon like the "X" from FontAwesome -->
            <% end %>
          </div>
        </div>
        <div class="border-top">
          <%= simple_form_for [@doctor, @appointment] do |f| %>
            <%= f.input :start_time,
              label: "Choose a slot:",
              as: :radio_buttons,
              collection_wrapper_tag: 'div',
              collection_wrapper_class: 'category-wrapper grid-display',
              item_wrapper_class: 'category-item',
              input_html: {class: 'category-selector'},
              collection: @available_timings.map { |hour| ["#{hour}:00", hour ] }
            %>
            <%# <%= f.input :end_time, as: :time, html5: true, input_html: { value: @date } %>
            <%= hidden_field_tag 'date', @date, data: {the_form_target: "modalDate"} %>
            <%= hidden_field_tag 'procedure', @procedure, data: {the_form_target: "modalProcedure"} %>
            <%= hidden_field_tag 'doctor_appointments', @doctor_appointments, data: {the_form_target: "modalDoctorAppointment"} %>
            <%= f.input :symptoms, label: "Describe your symptoms", input_html: { class: 'background-color-sec' } %>
            <%= f.input :additional_details, label: "Additional information:", input_html: { class: 'background-color-sec' } %>
            <div class="d-flex justify-content-center">
              <%= f.submit "Book Appointment", class: "btn btn-primary" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
 <div class="back-col">
  <% if @specialty.present? %>
    <h1 class= "text-center font-title">Select your prefered doctor for <%= @specialty.downcase %></h1>
  <% else %>
    <h1 class= "text-center font-title">Select your prefered doctor</h1>
  <% end %>
  <div class="d-flex">
      <div class="container disposition d-flex">
        <div class="wrapmrgn">
          <% @doctors.each do |user| %>
            <%full_name = "#{user.first_name} #{user.last_name}" %>
            <%# ------the whole DIV is now a button taking us to the doctors show page below %>
            <%= link_to user_path(user) do %>
              <div class="card-product btn bord-rad new-card-bg">
              <%# <%=link_to "see profile", user_path, class: "btn"  %>
                <div class="shadow bord-rad">
                  <%=image_tag user.image_url, class: "img-size img-thumbnail"%>
                </div>
                <div class="card-product-infos">
                  <h2><%=full_name %></h2>
                  <p><%=user.bio%></p>
                  <%=user.locations.first.name%>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class= "bord-rad shadow marg-right my-3" style="width: 600px; height: 600px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="body-container">
  <div class="bio-reviews-container">
    <div class="show-page-card align-items-center">
      <div class="show-page-photo-card">
        <%= image_tag @doctor.image_url%>
        <h2>Dr.<%= @doctor.first_name %> <%= @doctor.last_name %></h2>
        <% unless @reviews.empty? %>
          <% review_avg = 0 %>
          <% counter = 0 %>
          <p class="my-0"><% @reviews.each do |review| %>
              <% review_avg += review.rating %>
               <% counter += 1 %>
            <% end %>
            <% (review_avg / @reviews.length).times do  %>
              <i class="fa-solid fa-star fa-lg" style="color: #ffb503;"></i>
            <% end %>
          </p>
          <span style="font-size: 12px">(<%= counter %> reviews)</span>
        <% else %>
          <p>
            No reviews yet
          </p>
        <% end %>
        <p><strong>Specialty: <%= @doctor.specialty%></strong></p>
      </div>
      <div class="show-page-calendar-card h-100">
        <div class="calendar d-flex justify-content-between">
          <%# <input type="text" placeholder="Select Date.." data-controller="datepicker"> %>
          <%= form_with url: booking_appointment_path(
            params[:id],
            appointment_date: params[:appointment_date],
            procedure_id: params[:procedure_id],
            ), method: :get do |f| %>
            <div class="calendar-wrapper">
              <%= f.text_field :appointment_date,
                value: params[:appointment_date],
                class: "form-control",
                hidden: true,
                placeholder: "Type a keyword",
                # The Controller should Listen for a submit and capture the params[:appointment_date]
                data: { controller: "datepicker" }
              %>
              <div class="category-wrapper p-2">
                <h5 class="text-center mb-2">Select your procedure:</h5>
                <div class="category-grid">
                  <% @doctor.procedures.each do |procedure| %>
                    <div class="category-item">
                      <%= f.radio_button :procedure_id, procedure.id, class: 'form-check-input radio_buttons required category-selector', data: { style: 'ruby' }, id: "snippet_category_id_#{procedure.id}" %>
                      <%= f.label "snippet_category_id_#{procedure.id}", procedure.name, class: 'form-check-label collection_radio_buttons' %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="d-flex justify-content-end">
              <%= submit_tag "Check Availability", class: "btn btn-primary m-3" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>



    <div class="bio-card">
      <p class="title"><b>Biography </b></p>
      <div class="inner">
          <div><p><b>Establishment</b><br><i class="fa-solid fa-user-doctor fa-lg" style="color: #4a4e69;"></i> <%= @doctor.specialty %></p></div>
          <div><p><b>Year : <%= rand(1985..2004) %></b></p></div>
      </div>
      <div class="expertise">
        <p><b>Expertise & Procedures</b><br><i class="fa-solid fa-user-doctor fa-lg" style="color: #4a4e69;"></i> <%= @doctor.bio %></p>
      </div>
    </div>


    <div class="location-card">
      <p class="title"><b>Location</b></p>
      <div class="inside">
        <% @doctor.locations.each do |location| %>
          <i class="fa-solid fa-house-medical fa-lg" style="color: #4a4e69;"></i>
          <%= location.name %><span>: </span>
          <%= location.address %> <br><br>
        <% end %>
      </div>
    </div>
  </div>

  <div class="map-price-container">
    <div class="price-card">
      <p class="title"><b>Pricing</b></p>
      <div class="inside">
        <table class="table table-borderless">
          <tr>
            <th>Name</th>
            <th>Cost</th>
            <th>Duration</th>
          </tr>
          <% @doctor.procedures.each do |procedure| %>
          <tr>
            <th><%= procedure.name%></th>
            <th>£ <%= procedure.price %></th>
            <th><%= procedure.duration %> min</th>
          </tr>
          <% end %>
        </table>
      </div>
    </div>

    <%# --------MAP----DIV BELOW------------- %>
    <div class="sticky bord-rad shadow" style="width: 100%; height: 560px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <%# -------------MAP----DIV-----END------------- %>
  </div>
</div>



<div id="carouselExampleAutoplaying" class="carousel slide mb-5 px-3" data-bs-ride="carousel" data-bs-interval="3000">
  <div class="carousel-inner">
    <% @reviews.each_slice(3).with_index do |review_group, i| %>
      <div class="carousel-item <%= i == 0 ? "active" : "" %>">
        <div class="d-flex justify-content-between px-3">
          <% review_group.each do |review| %>
            <div class="card-review m-2">
              <p> Rating:
                <% review.rating.to_i.times do %>
                  <i class="fa-solid fa-star fa-beat" style="color: #ffb503;"></i>
                <% end %>
              </p>
              <p><%= review.comment %></p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>