config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index] do
    resources :appointments, only: [:new, :create]
  end

  # to delete
  resources :appointments, only: [:show, :index, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  # Defines the root path route ("/")
  # root "articles#index"
  get "/users/:id/booking_appointment", to: 'users#booking_appointment', as: 'booking_appointment'
  resources :users, only: [:show]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

  <%# This is the home page link here %>
    <%= link_to root_path do %>
      <%= image_tag "logo.jpg", class: "navbar-brand p-2 mx-2"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My appointments", appointments_path(current_user) , class: "nav-link btn-color" %>
          </li>
          <li class="nav-item active">
            <%# <%= image_tag "yusuf.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <%# I'm sorry but this image tag above looks horrible  %>
            <%= link_to "Log out",  destroy_user_session_path, class: "nav-link btn-color", data: {turbo_method: :delete} %>
          </li>
        <% else %>
          <li class="nav-item d-flex">
            <img src="https://images.emojiterra.com/google/noto-emoji/unicode-15/color/svg/1fa7a.svg" class="logo-stratoscope" />
            <%= link_to "Login", new_user_session_path, class: "nav-link login-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<%# Code Just Fun By Yusuf Uras Celikdemir  %>