config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index] do
    resources :appointments, only: [:new, :create]
  end

  # to delete
  resources :appointments, only: [:show, :index, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  # Defines the root path route ("/")
  # root "articles#index"
  get "/users/:id/booking_appointment", to: 'users#booking_appointment', as: 'booking_appointment'
  resources :users, only: [:show]
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :location
  has_many :procedures, through: :procedure_appointments
  enum :status, ["pending", "accepted", "declined"]
  belongs_to :patient, class_name: "User"
  belongs_to :doctor, class_name: "User"
  validates :symptoms, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true


end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_doctor, only: [:create]

  def index
    @user = current_user
    @appointments = @user.appointments_as_patient.all.to_a
  end

  def create
    # date = params[:appointment_date] | We need to get the DD/MM/YYYY from User's controller
    @appointment = Appointment.new(appointment_params)
    @appointment.patient = current_user
    @appointment.doctor = @doctor
    # End time will be defined by calculating the start_time + procedure.duration
    # The Location can't be the first by default, it needs to be the specific one
    @appointment.location = @doctor.locations.first
    procedure_name = params[:procedure]
    procedure_duration = Procedure.find_by(name: procedure_name).duration
    year = params[:date].to_date.year
    month = params[:date].to_date.month
    day = params[:date].to_date.day
    hour = params[:appointment][:start_time]
    minute = 0.to_s
    @appointment.start_time = Time.new(year, month, day, hour, minute, 0, 0)
    @appointment.end_time = Time.new(year, month, day, hour, minute, 0, 0) + (procedure_duration * 60)
    if @appointment.save
      redirect_to appointments_path
    else
      redirect_to user_path(@doctor), status: :unprocessable_entity
    end
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def destroy
  @appointment = Appointment.find(params[:id])
  @appointment.destroy
  redirect_to appointments_path, status: :see_other
  end

  private

  def set_doctor
    @doctor = User.find(params[:user_id])
  end

  def appointment_params
    params.require(:appointment).permit(:symptoms, :start_time, :additional_details)
  end
end

app/views/appointments/index.html.erb
<div class="mrgn-x bgrnd-col my-5">
  <div class="text-center marg-bot">
    <h1><u>My appointments</u></h1>
  </div>
  <h3>Upcoming appointments</h3>
  <div>
    <% @appointments.sort_by(&:start_time).each do |appointment| %>
      <% if Time.now < appointment.start_time %>
        <div class="bcg-col p-3 hr d-flex justify-content-between">
          <div class="px-3 pt-3">
            <u>Appointment with:</u>
            <strong><p>Dr. <%= appointment.doctor.first_name %> <%=appointment.doctor.last_name%></p></strong>
            <u>Location:</u>
            <strong><p><%= appointment.location.address %></p></strong>
            <u>Appointment date:</u>
            <strong><p><%= appointment.start_time.strftime("%a %e %b, %l %p") %></p></strong>
            <u>Patient's symptoms:</u>
            <strong><p><%= appointment.symptoms %></p></strong>
          </div>
                  <div class="mid-alignment">
                <%= link_to appointment_path(appointment),
                  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                  <i class="fa-solid fa-circle-xmark fa-xl"></i>
                  <% end %>

                <%=link_to user_path(appointment.doctor) do %>
                  <div class="btn btn-primary chng-color butt-style mrgintop marg-change">
                    <span    class="col-text">Book again with <%=appointment.doctor.first_name%></span>
                  </div>
                <%end%>
          </div>
        </div>

      <%end%>
    <%end%>

  <h3>Previous appointments</h3>
  <% @appointments.each do |appointment| %>
      <% if Time.now > appointment.start_time %>
    <div class="mt-3 hr">
      <div class="bcg-col d-flex justify-content-between">
          <div class="px-3 pt-3">
            <u>Appointment with:</u>
            <strong><p>Dr. <%= appointment.doctor.first_name %> <%=appointment.doctor.last_name%></p></strong>
            <u>Location:</u>
            <strong><p><%= appointment.location.address %></p></strong>
            <u>Appointment date:</u>
            <strong><p><%= appointment.start_time.strftime("%a %e %b, %l %p") %></p></strong>
            <u>Patient's symptoms:</u>
            <strong><p><%= appointment.symptoms %></p></strong>
          </div >
          <div class="ms-5 mrgintop align-items-center mid-alignment">
            <%=link_to user_path(appointment.doctor) do %>
              <div class="btn btn-primary chng-color butt-style marg-change">
              <span class="col-text">Book again with <%=appointment.doctor.first_name%></span>
            <%end%>
              </div>
            <%= link_to "Leave a review", new_appointment_review_path(appointment), class: "sec-bttn p-2 px-3" %>
          </div>

      <%end%>
    </div>
  <% end %>
</div>

<%# to delete %>

app/views/appointments/show.html.erb
<p>appointments-show-page</p>


<div class="container border border-warning">

  <div class="confirmation-details">
    <p>You have an appointment confirmed with: <b><%= @appointment.doctor.first_name %> <%= @appointment.doctor.last_name %></b></p>
    <p> on </p><p><%= @appointment.start_time.strftime("%A, %d %b %Y %l:%M %p") %></p>
    <%= image_tag((@appointment.doctor.image_url), size: "200") %>

  </div>
  <br><p>     Your Booking has been confirmed! Thank you!</p>
</div>
<div>
  <%= link_to "My Dashboard", appointments_path(current_user) %>
</div>

<%= link_to "Cancel appointment",
  appointment_path(@appointment),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>